Feature/crud operations
Deniskoltovich/TradeProcessor pull request #5
Opened 2023-06-27 13:45 UTC by Deniskoltovich

2023-06-28 14:02 UTC, rylkorom commented on trade_processor/accounts/views/user_views.py
> +        url_path='subscriptions/add',
/add убрать

2023-06-28 14:05 UTC, rylkorom commented on trade_processor/orders/services/order_create_service.py
> +    def execute(user, data):
execute не информативно

2023-06-28 14:05 UTC, rylkorom commented on trade_processor/orders/services/order_create_service.py
> +        serializer.is_valid(raise_exception=True)
это во вьюхах

2023-06-28 18:32 UTC, Deniskoltovich commented on trade_processor/accounts/models.py
> +class PortfolioAsset(models.Model):
это m2m, но с доп полем, чтобы хранить количество активов
    assets = models.ManyToManyField(
        Asset, through='PortfolioAsset', verbose_name='Assets'
    )

2023-06-28 18:37 UTC, Deniskoltovich commented on trade_processor/accounts/views/portfolio_views.py
> +    queryset = Portfolio.objects.all()
там либо это, либо get_queryset определить
по умолчанию none

2023-06-28 18:38 UTC, Deniskoltovich commented on trade_processor/accounts/views/user_views.py
> +        methods=['get'],
я попробовал майпай очень сильно везде ругается

2023-06-28 19:02 UTC, Deniskoltovich commented on trade_processor/config/jwt_middleware.py
> +    def __call__(self, request):
согласен было не оч, теперь миддлевер отвечает за то чтобы прочитать токен и положить инфу в реквест (или выкинуть ошибку), а Auth класс за то, чтобы аутентифицировать юзера по инфе в реквесте

2023-06-29 10:57 UTC, rylkorom requested changes
общее замечание - тесты не по AAA

2023-06-29 10:57 UTC, rylkorom commented on trade_processor/accounts/views/user_views.py
> +        methods=['get'],
запятую ставь

2023-06-29 10:57 UTC, rylkorom commented on trade_processor/entrypoint_web.sh
> +python manage.py migrate
почему сначала мигрируешь, а потом только запускаешь сервер

2023-06-29 10:57 UTC, rylkorom commented on trade_processor/recommendations/services/create_recommendation_service.py
> +            pass
pass???

2023-06-30 09:54 UTC, rylkorom requested changes
Общее замечание - серализаторы, чекнешь мой коммент
второе замечание - должен на уровне контроллеров передовать данные  в сериализатор и там возвращать респонзы, в сервисном слое только логика без сериализации

2023-06-30 09:54 UTC, rylkorom commented on trade_processor/accounts/views/user_views.py
> +        'update': user_serializers.UpdateUserByAdminSerializer,
почему не на все методы + где разграничения в сериализации для обычного юзера и админа - чекни, как у Назара, я ему сегодня объяснил

2023-06-30 09:54 UTC, rylkorom commented on trade_processor/accounts/views/user_views.py
> +        return Response(
лучше тут сериалзиовать, это controller твой

2023-07-01 14:04 UTC, rylkorom reviewed
Код просто сказка, оставил 2 небольших коммента + я бы ещё на твоём месте где-нибудь навесил декораторы atomic для транзакционности. Смотри сам, код можешь мержить, а можешь исправить и сам смержить

2023-07-01 14:04 UTC, rylkorom commented on trade_processor/recommendations/views.py
> +        'list': (IsOwner,),
Я бы ещё добавил для удаления, Но это так, микро-доеб

2023-07-02 11:47 UTC, merged